name: Bug Report
description: Report a problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        - To help us address issues efficiently, please provide clear and detailed bug reports. Reports lacking sufficient information may not be prioritized for review.
        - Before reporting, search our [existing issues](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues?q=is%3Aissue) and [changelog](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases) to see if the issue has already been addressed.
  - type: input
    attributes:
      label: "MAX Plugin Version"
      placeholder: "e.g., 5.4.4"
    validations:
      required: true
  - type: input
    attributes:
      label: "Unity Version"
      placeholder: "e.g., 2020.3.36f1"
    validations:
      required: true
  - type: input
    attributes:
      label: "Device/Platform Info"
      description: "Is the problem affecting any specific devices or platforms?"
      placeholder: "e.g., Android 8.1, iOS 15, Google Pixel 5a, etc."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Current Behavior"
      description: "A concise description of what you're experiencing."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "A concise description of what you expected to happen."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "How to Reproduce"
      description: "Step-by-step instructions, code snippets, or other details to reproduce the issue."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Reproducible in the demo app?"
      description: Please try and reproduce the issue in the [demo app](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin)
      options:
        - "Yes"
        - "No"
        - "Not Tested"
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional Info"
      description: |
        - If applicable, include any info to provide further context, such as images, videos, or logs after [enabling verbose logging](https://developers.applovin.com/en/max/unity/overview/advanced-settings#enable-verbose-logging).
        - If you don't want to post media publicly, please submit your file(s) in a [support request](https://support.applovin.com/hc/en-us/requests/new) with subject 'Issue #<ISSUE_NUMBER>: <ISSUE_LINK>' after filing this issue with a note saying you will do so here.
      placeholder: "Tip: Attach files by clicking this area and dragging files in"
    validations:
      required: false
